export const midgameMilestones = [
  {
    id: 'cake_ready',
    label: 'Cake Production Ready',
    category: 'Base',
    prerequisites: [],
    reason: 'Keeps breeding and high-value Pal production moving without manual bottlenecks.',
  },
  {
    id: 'ore_mine',
    label: 'Ore Mine Established',
    category: 'Base',
    prerequisites: [],
    reason: 'Creates a dependable ore supply for every production upgrade that follows.',
  },
  {
    id: 'electricity',
    label: 'Electricity Online',
    category: 'Base',
    prerequisites: [],
    reason: 'Powers the advanced stations needed for the next production tier.',
  },
  {
    id: 'refined_ingots',
    label: 'Refined Ingot Production',
    category: 'Production',
    prerequisites: ['ore_mine', 'electricity'],
    reason: 'Opens the material tier required by stronger equipment and advanced structures.',
  },
  {
    id: 'two_bases',
    label: 'Second Base Established',
    category: 'Base',
    prerequisites: [],
    reason: 'Adds the space and workforce capacity needed for specialized resource production.',
  },
  {
    id: 'guild_storage',
    label: 'Guild Chest in Both Bases',
    category: 'Base',
    prerequisites: ['two_bases'],
    reason: 'Keeps essential materials available across both operating bases.',
  },
  {
    id: 'third_tower',
    label: 'Third Tower Defeated',
    category: 'Progression',
    prerequisites: [],
    reason: 'Moves world progression forward and confirms the current combat setup is ready.',
  },
  {
    id: 'pure_quartz',
    label: 'Pure Quartz Quarry',
    category: 'Production',
    prerequisites: [],
    reason: 'Secures a steady supply of Pure Quartz for advanced electronic production.',
  },
  {
    id: 'electric_furnace',
    label: 'Electric Furnace',
    category: 'Production',
    prerequisites: ['electricity', 'refined_ingots'],
    reason: 'Automates high-tier smelting and prepares the base for Pal Metal production.',
  },
  {
    id: 'pal_metal_ingots',
    label: 'Pal Metal Ingot Production',
    category: 'Production',
    prerequisites: ['electric_furnace', 'pure_quartz'],
    reason: 'Supplies the advanced metal needed for late mid-game equipment and structures.',
  },
  {
    id: 'production_assembly_line_2',
    label: 'Production Assembly Line II',
    category: 'Production',
    prerequisites: ['electricity', 'pure_quartz'],
    reason: 'Unlocks Bio Batteries and higher-tier production materials.',
  },
  {
    id: 'coal_quarry',
    label: 'Coal Quarry',
    category: 'Production',
    prerequisites: ['two_bases'],
    reason: 'Removes the repeating Coal shortage that stalls Refined Ingot production.',
  },
  {
    id: 'crude_oil_extraction',
    label: 'Crude Oil Extraction',
    category: 'Production',
    prerequisites: ['two_bases', 'production_assembly_line_2'],
    reason: 'Two oil nodes are already secured at the second base \u2014 turn them into passive income.',
  },
];
